# fly.toml app configuration file generated for seb-nestjs-graphql on 2023-09-29T19:01:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seb-nestjs-graphql"
primary_region = "lhr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  HOST = "0.0.0.0"
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
