# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - uses: borales/actions-yarn@v4
      with:
        cmd: test
        env: 
          AUTH_SECRET: blabbablabba
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

    - uses: borales/actions-yarn@v4
      with:
        cmd: test:e2e
        env: 
          AUTH_SECRET: blabbablabba
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
